[functions.createPayment]
verify_jwt = false

[functions.mp-oauth-callback]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.checkPaymentStatus]
verify_jwt = false

[functions.getMpOauthUrl]
verify_jwt = false
